### ISSUE TITLE
{"code": 500, "error": true}

### ISSUE THREAD

**Issue by simukka** [twilio/stashboard#10]
After following the directions and deploying to app engine, I only get this "{"code": 500, "error": true}". I've tried several deployments and even downgraded to version 1.1.5. 

Here's what the log says:
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/**init**.py", line 511, in **call**
    handler.get(_groups)
  File "/base/data/home/apps/rm-status/1.345968616742131117/utils/authorized.py", line 57, in check_ssl
    handler_method(self, *args, *_kwargs)
  File "/base/data/home/apps/rm-status/1.345968616742131117/handlers/site.py", line 142, in get
    td = default_template_data()
  File "/base/data/home/apps/rm-status/1.345968616742131117/handlers/site.py", line 71, in default_template_data
    greeting = users.create_login_url("/")
  File "/base/python_runtime/python_lib/versions/1/google/appengine/api/users.py", line 223, in create_login_url
    raise NotAllowedError
NotAllowedError

Any ideas?

**Comment by simukka** [comment]
Update: I'm able to get it working on a local environment so this leads me to believe it's an issue with appengine. I'm wondering if its because the authentication method is set to "This domain only..." so I'm able to authenticate with my Google App account instead of Google Accounts.

**Comment by chuck** [comment]
I'm seeing this also - any updates here? Does stashboard not work with Google Apps? Or am I misunderstanding the problem?

**Comment by dantman** [comment]
I get this error when deploying to an app with the Google Accounts api set to a specific apps domain, but not when deploying to an app with the default, 'allow everyone' setting.

**Comment by shaiguitar** [comment]
Seen this as well.

**Comment by kyleconroy** [comment]
This hasn't been reported anytime lately, so I think it's been fixed.
